version: "3.9"

services:

  product-postgres:
    image: postgres:15
    container_name: product-postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: krishtomar2005
    ports:
      - "5432:5432"
    networks:
      - cloud-network

  order-postgres:
    image: postgres:15
    container_name: order-postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: krishtomar2005
    ports:
      - "5433:5432"
    networks:
      - cloud-network

  product-service:
    image: product-service:2.0
    container_name: product-service
    ports:
      - "8093:8092"   # âœ… FIXED (host:container)
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-postgres:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: krishtomar2005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - product-postgres
    networks:
      - cloud-network

  order-service:
    image: order-service:1.0
    container_name: order-service
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-postgres:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: krishtomar2005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: mysecretkeymysecretkeymysecretkey12
    depends_on:
      - order-postgres
      - product-service
    networks:
      - cloud-network

networks:
  cloud-network:
    external: true
